apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beemoviebot.fullname" . }}
  labels:
    app: beemoviebot-chart
    version: {{ .Values.image.tag }}
    circleci.com/component-name: "beemoviebot-chart"
    circleci.com/version: {{ .Values.image.tag | quote }}
  annotations:
    circleci.com/project-id: {{ .Values.circleci.project_id | quote }}
    circleci.com/helm-revision-number: {{ .Release.Revision | quote }}
    circleci.com/pipeline-id: {{ .Values.circleci.pipelineId | quote }}
    circleci.com/workflow-id: {{ .Values.circleci.workflowId | quote }}
    circleci.com/job-number: {{ .Values.circleci.jobNumber | quote }}
    circleci.com/component-name: "beemoviebot-chart"
    circleci.com/version: {{ .Values.image.tag | quote }}
    circleci.com/restore-version-enabled: {{ .Values.circleci.restoreversionenabled | quote }}
    circleci.com/scale-component-enabled: {{ .Values.circleci.scalecomponentenabled | quote }}
    circleci.com/restart-component-enabled: {{ .Values.circleci.restartcomponentenabled | quote }}
    circleci.com/retry-release-enabled: {{ .Values.circleci.retryreleaseenabled | quote }}
    circleci.com/promote-release-enabled: {{ .Values.circleci.promotereleaseenabled | quote }}
    circleci.com/cancel-release-enabled: {{ .Values.circleci.cancelreleaseenabled | quote }}
    # The above 3 do not work. Need to figure out how to get those dynamically.
    # Look into how on-prem got them as annotations 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: beemoviebot-chart
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: beemoviebot-chart
        version: {{ .Values.image.tag }}
        circleci.com/component-name: "beemoviebot-chart"
        circleci.com/version: {{ .Values.image.tag | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beemoviebot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: CLIENT_ID
            - name: BEEMOVIEBOT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: BEEMOVIEBOT
            - name: PteroToken
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: PteroToken   
            - name: CIRCLE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: CIRCLE_TOKEN    
            - name: BALLDONTLIEAPITOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: BALLDONTLIEAPITOKEN  
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
