apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beemoviebot.fullname" . }}
  labels:
    app: beemoviebot-chart
    version: {{ .Values.image.tag }}
  annotations:
    circleci.com/project-id: {{ .Values.circleci.project_id }}
    circleci.com/helm-revision-number: {{ .Release.Revision | quote }}
    circleci.com/pipeline-id: {{ .Values.circleci.pipelineId }}
    circleci.com/workflow-id: {{ .Values.circleci.workflowId }}
    circleci.com/job-number: {{ .Values.circleci.jobNumber | quote }}
    # The above 3 do not work. Need to figure out how to get those dynamically.
    # Look into how on-prem got them as annotations 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: beemoviebot-chart
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: beemoviebot-chart
        version: {{ .Values.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beemoviebot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
